// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_recent_review_stats.sql

package sqlcgen

import (
	"context"
)

const getRecentReviewStats = `-- name: GetRecentReviewStats :one
SELECT COUNT(*)::integer AS review_count, COALESCE(SUM(rating), 0)::float8 AS rating_sum
FROM (
    SELECT rating
    FROM reviews
    WHERE place_id = $1
    ORDER BY created_at DESC
    LIMIT $2
) q
`

type GetRecentReviewStatsParams struct {
	PlaceID string `json:"place_id"`
	Limit   int32  `json:"limit"`
}

type GetRecentReviewStatsRow struct {
	ReviewCount int32   `json:"review_count"`
	RatingSum   float64 `json:"rating_sum"`
}

func (q *Queries) GetRecentReviewStats(ctx context.Context, arg GetRecentReviewStatsParams) (GetRecentReviewStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getRecentReviewStats, arg.PlaceID, arg.Limit)
	var i GetRecentReviewStatsRow
	err := row.Scan(&i.ReviewCount, &i.RatingSum)
	return i, err
}
