// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Review struct {
	ID        uuid.UUID `json:"id"`
	PlaceID   string    `json:"place_id"`
	UserID    uuid.UUID `json:"user_id"`
	Rating    float64   `json:"rating"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Station struct {
	ID          uuid.UUID       `json:"id"`
	PlaceID     string          `json:"place_id"`
	Name        string          `json:"name"`
	Address     sql.NullString  `json:"address"`
	Latitude    sql.NullFloat64 `json:"latitude"`
	Longitude   sql.NullFloat64 `json:"longitude"`
	TotalScore  float64         `json:"total_score"`
	ReviewCount int32           `json:"review_count"`
	Summary     sql.NullString  `json:"summary"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}
