// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review_insert.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
    place_id,
    user_id,
    rating
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, place_id, user_id, rating, created_at, updated_at
`

type CreateReviewParams struct {
	PlaceID string    `json:"place_id"`
	UserID  uuid.UUID `json:"user_id"`
	Rating  float64   `json:"rating"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview, arg.PlaceID, arg.UserID, arg.Rating)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.UserID,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
