// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: station_get_stations.sql

package sqlcgen

import (
	"context"
)

const countStations = `-- name: CountStations :one
SELECT COUNT(*)::bigint AS total
FROM station
`

func (q *Queries) CountStations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStations)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getStations = `-- name: GetStations :many
SELECT
    id,
    place_id,
    name,
    address,
    latitude,
    longitude,
    total_score,
    review_count,
    summary,
    created_at,
    updated_at
FROM station
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetStationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetStations(ctx context.Context, arg GetStationsParams) ([]Station, error) {
	rows, err := q.db.QueryContext(ctx, getStations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Station
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.ID,
			&i.PlaceID,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.TotalScore,
			&i.ReviewCount,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
