// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: station_get_by_place_id.sql

package sqlcgen

import (
	"context"
)

const getStationByPlaceID = `-- name: GetStationByPlaceID :one
SELECT
    id,
    place_id,
    name,
    address,
    latitude,
    longitude,
    total_score,
    review_count,
    summary,
    created_at,
    updated_at
FROM station
WHERE place_id = $1
`

func (q *Queries) GetStationByPlaceID(ctx context.Context, placeID string) (Station, error) {
	row := q.db.QueryRowContext(ctx, getStationByPlaceID, placeID)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.PlaceID,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.TotalScore,
		&i.ReviewCount,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
