// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upsert_score.sql

package sqlcgen

import (
	"context"
)

const upsertStationScore = `-- name: UpsertStationScore :exec
INSERT INTO station (
    place_id,
    name,
    total_score,
    review_count,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    now()
)
ON CONFLICT (place_id) DO UPDATE SET
    total_score = EXCLUDED.total_score,
    review_count = EXCLUDED.review_count,
    updated_at = now()
`

type UpsertStationScoreParams struct {
	PlaceID     string  `json:"place_id"`
	Name        string  `json:"name"`
	TotalScore  float64 `json:"total_score"`
	ReviewCount int32   `json:"review_count"`
}

func (q *Queries) UpsertStationScore(ctx context.Context, arg UpsertStationScoreParams) error {
	_, err := q.db.ExecContext(ctx, upsertStationScore,
		arg.PlaceID,
		arg.Name,
		arg.TotalScore,
		arg.ReviewCount,
	)
	return err
}
